services:
  php-fpm:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./php-src:/php-src
      - ./app:/app
    environment:
      CONFIGURE_OPTIONS: ${CONFIGURE_OPTIONS}
    working_dir: /php-src
    command: /php-src/php/sbin/php-fpm
    cap_add:
      - SYS_PTRACE
