services:
  php-fpm:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./php-src:/php-src
      - ./app:/app
    environment:
      CONFIGURE_OPTIONS: ${CONFIGURE_OPTIONS}
    working_dir: /php-src
    command: /php-src/php/sbin/php-fpm
    cap_add:
      - SYS_PTRACE
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
volumes:
  mysql_data:
