services:
  nginx:
    image: nginx:1.26
    ports:
      - '8000:80'
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  php-fpm:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./php-src:/php-src
      - ./app:/app
    environment:
      CONFIGURE_OPTIONS: ${CONFIGURE_OPTIONS}
      USE_ZEND_DTRACE: 1
    working_dir: /php-src
    command: /php-src/php/sbin/php-fpm
    cap_add:
      - SYS_PTRACE
      - CAP_SYS_ADMIN
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
volumes:
  mysql_data:

