name: CI
on: [push]

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make GIT_OPTION=--depth=1

      - run: docker compose run --rm php-fpm /php-src/php/bin/php -v

      - run: make dump-opcode
      - run: make dump-ast

