name: CI
on: [push]

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make

      - run: docker compose run --rm php-fpm /php-src/php/bin/php -v

